services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: mooc
      POSTGRES_USER: codely
      POSTGRES_PASSWORD: c0d3ly7v
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./databases/codely.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data:
